// Code generated by cmd/internal-tools/genrules; DO NOT EDIT.
// Source: packs/agent-tool/rules/*.yaml

package agenttool

import "github.com/shibuiwilliam/archfit/internal/model"

// GeneratedRules returns rule metadata loaded from YAML. Resolver fields are
// nil — pack.go wires them by ID.
func GeneratedRules() []model.Rule {
	return []model.Rule{
		{
			ID:               "P2.SPC.010",
			Principle:        model.P2SpecFirst,
			Dimension:        "SPC",
			Title:            "Tool ships a versioned JSON output schema",
			Severity:         model.SeverityWarn,
			EvidenceStrength: model.EvidenceStrong,
			Stability:        model.StabilityStable,
			Weight:           1,
			Rationale:        "An agent-driven tool's machine-readable output is a contract. Without a versioned, discoverable schema, downstream agents cannot tell additive changes from breaking ones. This rule looks for a JSON Schema file under schemas/ whose content declares a top-level $id and is referenced from a schema_version field in documentation or in the schema itself.",
			Remediation: model.Remediation{
				Summary:     "Place a JSON Schema at schemas/output.schema.json (or similar) with a top-level $id identifying it unambiguously, and emit a schema_version field in your tool's JSON output that matches.",
				GuideRef:    "docs/rules/P2.SPC.010.md",
				AutoFixable: false,
			},
		},
		{
			ID:               "P7.MRD.002",
			Principle:        model.P7MachineReadability,
			Dimension:        "MRD",
			Title:            "Agent-tool repository has a CHANGELOG.md at the root",
			Severity:         model.SeverityWarn,
			EvidenceStrength: model.EvidenceStrong,
			Stability:        model.StabilityStable,
			Weight:           1,
			Rationale:        "Agents driving a tool need a machine-readable record of what changed between versions. CHANGELOG.md is the lightest, most widely recognized signal. Keep-a-changelog.com and SemVer co-evolve; a tool that ships without one forces agents to diff the repository or infer changes from commit titles.",
			Remediation: model.Remediation{
				Summary:     "Add CHANGELOG.md at the repository root following the Keep a Changelog format. Minimum sections: Unreleased, then versioned releases with Added / Changed / Removed subsections.",
				GuideRef:    "docs/rules/P7.MRD.002.md",
				AutoFixable: false,
			},
		},
		{
			ID:               "P7.MRD.003",
			Principle:        model.P7MachineReadability,
			Dimension:        "MRD",
			Title:            "Agent-tool repository records ADRs under docs/adr/",
			Severity:         model.SeverityWarn,
			EvidenceStrength: model.EvidenceStrong,
			Stability:        model.StabilityStable,
			Weight:           1,
			Rationale:        "Architecture Decision Records are the canonical way to surface irreversible design choices to agents. When an agent is asked to refactor an agent-tool, the ADR log tells it which decisions are load-bearing (and why) versus which are accidents of history. This rule fires when the repo ships a CLI (has cmd/) but no docs/adr/ directory exists.",
			Remediation: model.Remediation{
				Summary:     "Create docs/adr/ and seed it with an initial ADR documenting the architecture overview. Use YAML frontmatter (id, title, status, date).",
				GuideRef:    "docs/rules/P7.MRD.003.md",
				AutoFixable: false,
			},
		},
	}
}
